version: "3.9"
services:
  backend:
    build: .
    container_name: fiber-backend
    ports:
      - "3000:3000"
#     environment:
#       - DB_HOST=db
#       - DB_USER=postgres
#       - DB_PASS=postgres
#       - DB_NAME=mydb
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     container_name: fiber-db
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: mydb
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
